name: CI Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up GCC and make
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential

      # Debug build
      - name: Build in debug mode
        run: |
          make clean
          make debug
      
      # Release build
      - name: Build in release mode
        run: |
          make clean
          make release

      # Run tests
      - name: Run tests
        run: |
          ./debug/exefile
